"""AKTU 1st year - Electrical (BEE101), Electronics (BEC101), Programming for Problem Solving (BCS101), Mechanical (BME101)."""
from database.aktu_helpers import L, N, S, chapter, merge_chapters, to_subject

OUTLINE_NOTE = ("Chapter outline built from the standard topics of this course under AKTU. Unit titles and order can differ in your "
                "session's official syllabus, so compare with the PDF on aktu.ac.in.")

ELECTRICAL = {
    "slug": "bee101", "codes": "BEE101 / BEE201", "name": "Fundamentals of Electrical Engineering", "category": "Engineering Science",
    "credits": 3, "ltp": "2-1-0", "semester_group": "Sem 1 or Sem 2 (Electrical / Electronics group)",
    "syllabus_status": "outline", "status_note": OUTLINE_NOTE,
    "about": "DC and AC circuits, three-phase systems, transformers, motors and electrical safety.",
    "chapters": [
        chapter("DC Circuits",
                ["Ohm's law, KCL and KVL", "Series and parallel circuits", "Mesh and nodal analysis", "Superposition theorem", "Thevenin's and Norton's theorems", "Maximum power transfer theorem"],
                "DC circuit analysis uses Kirchhoff's laws to find currents and voltages. Network theorems simplify complicated circuits into a single source and a single resistance.",
                ["KCL: algebraic sum of currents at a node is zero. KVL: algebraic sum of voltages around a loop is zero.",
                 "Superposition applies only to linear circuits; replace other voltage sources by short circuits and current sources by open circuits.",
                 "Thevenin equivalent: Vth = open-circuit voltage, Rth = resistance seen with sources removed.",
                 "Maximum power is transferred when load resistance equals source (Thevenin) resistance."],
                ["V = I R,   P = V I = I^2 R", "Series: Req = R1 + R2 + ...;   Parallel: 1/Req = 1/R1 + 1/R2 + ...", "Max power: RL = Rth and Pmax = Vth^2/(4 Rth)"],
                [S("State Kirchhoff's current and voltage laws."), S("State maximum power transfer theorem."), S("What is the difference between Thevenin's and Norton's equivalents?"),
                 L("State and explain Thevenin's theorem with an example."), L("Using mesh analysis find the currents in a two-loop network."),
                 L("State and prove the maximum power transfer theorem for a DC circuit."),
                 N("A 12 V source with internal resistance 2 ohm feeds a load. Find the load resistance for maximum power and the power delivered.", "RL = 2 ohm; I = 12/4 = 3 A; P = I^2 RL = 18 W.")]),
        chapter("Steady State Analysis of AC Circuits",
                ["Sinusoidal quantities: average, RMS, form factor", "Phasor representation", "R, L, C in AC circuits", "Series RLC circuit", "Power, power factor", "Resonance in series and parallel circuits"],
                "An AC voltage varies sinusoidally with time and is handled using phasors. Inductors and capacitors oppose AC through reactance, and in a series RLC circuit the current peaks at the resonant frequency.",
                ["RMS value of a sine wave = peak/sqrt(2); average value over half cycle = 2 x peak/pi.",
                 "In an inductor current lags voltage by 90 degrees; in a capacitor current leads by 90 degrees.",
                 "Power factor = cos(phi) = R/Z; real power P = V I cos(phi).",
                 "At series resonance XL = XC, impedance is minimum (= R) and current is maximum.",
                 "Quality factor Q = XL/R measures sharpness of resonance."],
                ["XL = 2 pi f L,   XC = 1/(2 pi f C)", "Z = sqrt(R^2 + (XL - XC)^2)", "P = V I cos(phi),  Q = V I sin(phi),  S = V I", "Resonant frequency f0 = 1/(2 pi sqrt(LC))"],
                [S("Define RMS value and form factor."), S("What is power factor? Why is a low power factor undesirable?"), S("What is resonance in a series RLC circuit?"),
                 L("Derive the impedance, current and phase angle of a series RLC circuit."), L("Explain resonance in a series RLC circuit and derive the resonant frequency and Q-factor."),
                 L("Explain active, reactive and apparent power with the power triangle."),
                 N("A series circuit has R = 10 ohm, XL = 20 ohm, XC = 10 ohm across 230 V. Find the current and power factor.", "Z = sqrt(100 + 100) = 14.14 ohm; I = 230/14.14 = 16.3 A; pf = 10/14.14 = 0.707 lagging.")]),
        chapter("Three-Phase Circuits and Magnetic Circuits",
                ["Three-phase voltage generation", "Star and delta connections", "Line and phase quantities", "Power in three-phase circuits", "Magnetic circuits: MMF, flux, reluctance", "Hysteresis and eddy current losses"],
                "A three-phase supply has three voltages 120 degrees apart and delivers power more smoothly and economically than single phase. Magnetic circuits behave like electrical circuits, with MMF as the source, flux as the current and reluctance as the resistance.",
                ["Star: line voltage = sqrt(3) x phase voltage; line current = phase current.",
                 "Delta: line voltage = phase voltage; line current = sqrt(3) x phase current.",
                 "Three-phase power P = sqrt(3) VL IL cos(phi) for balanced loads.",
                 "Reluctance S = l/(mu A); flux = MMF/reluctance.",
                 "Laminated cores reduce eddy current loss; soft magnetic materials reduce hysteresis loss."],
                ["P = sqrt(3) VL IL cos(phi)", "MMF = N I,   flux = MMF/S,   S = l/(mu0 mur A)", "Eddy loss is proportional to f^2 Bm^2 t^2"],
                [S("Write the relation between line and phase voltage in a star connection."), S("Define reluctance and MMF."), S("Why are transformer cores laminated?"),
                 L("Derive the relation between line and phase quantities in star and delta connected systems."), L("Compare electric and magnetic circuits."),
                 L("Explain hysteresis and eddy current losses and how they are reduced."),
                 N("A balanced star load takes 10 A from a 400 V line supply at power factor 0.8. Find the power.", "P = sqrt(3) x 400 x 10 x 0.8 = 5.54 kW.")]),
        chapter("Transformers and Electrical Machines",
                ["Single-phase transformer: construction and working", "EMF equation", "Losses and efficiency", "DC motor: principle and types", "Three-phase induction motor: principle, slip", "Single-phase motors (introduction)"],
                "A transformer changes AC voltage level using mutual induction with no moving parts. A DC motor produces torque from the interaction of field flux and armature current, and an induction motor runs at slightly less than synchronous speed.",
                ["Transformer works only on AC; the ratio of voltages equals the ratio of turns.",
                 "Efficiency is maximum when copper loss equals iron loss.",
                 "Back EMF in a DC motor opposes the supply and regulates the armature current.",
                 "Slip is the fractional difference between synchronous speed and rotor speed.",
                 "Induction motor is rugged, cheap and the most widely used industrial motor."],
                ["E1/E2 = N1/N2 = V1/V2 = I2/I1", "EMF equation: E = 4.44 f N phi-m", "Synchronous speed Ns = 120 f / P;  slip s = (Ns - Nr)/Ns", "DC motor: Eb = V - Ia Ra"],
                [S("Why is a transformer rated in kVA and not kW?"), S("What is back EMF in a DC motor?"), S("Define slip of an induction motor."),
                 L("Explain the construction and working of a single-phase transformer and derive its EMF equation."), L("Explain the working principle of a three-phase induction motor."),
                 L("Explain the types of DC motors and their applications."),
                 N("A transformer has 1000 primary turns on a 2200 V supply and a 220 V secondary. Find the number of secondary turns.", "N2 = N1 x V2/V1 = 100 turns."),
                 N("A 4-pole induction motor runs on 50 Hz at 1440 rpm. Find slip.", "Ns = 1500 rpm; s = 60/1500 = 0.04 (4%).")]),
        chapter("Electrical Installations and Safety",
                ["Components of a low-tension distribution system", "Fuse, MCB, ELCB/RCCB", "Earthing", "Types of wires and cables", "Batteries and UPS (introduction)", "Energy calculation and tariff", "Electrical safety"],
                "Safe electrical installations use protective devices such as fuses and MCBs and a proper earthing system. Understanding units of energy and power also helps you estimate and reduce electricity bills.",
                ["A fuse melts on overcurrent; an MCB trips and can be reset.",
                 "ELCB/RCCB protects people by tripping on earth leakage current.",
                 "Earthing gives a low-resistance path for fault current and keeps metal bodies at safe potential.",
                 "Energy in kWh = power in kW x time in hours.",
                 "Never work on a live circuit; switch off, isolate and test first."],
                ["Energy (kWh) = P(kW) x t(h)", "Cost = units consumed x tariff per unit"],
                [S("Differentiate between a fuse and an MCB."), S("Why is earthing necessary?"), S("What does an RCCB do?"),
                 L("Explain the types of earthing and why it is required."), L("Write a note on electrical safety precautions in a house."),
                 N("A 1.5 kW heater runs 2 hours daily for 30 days. Find the energy consumed and the bill at Rs 6 per unit.", "Energy = 1.5 x 2 x 30 = 90 kWh; bill = Rs 540.")]),
    ],
}

ELECTRONICS = {
    "slug": "bec101", "codes": "BEC101 / BEC201", "name": "Fundamentals of Electronics Engineering", "category": "Engineering Science",
    "credits": 3, "ltp": "2-1-0", "semester_group": "Sem 1 or Sem 2 (Electrical / Electronics group)",
    "syllabus_status": "outline", "status_note": OUTLINE_NOTE,
    "about": "Diodes, transistors, op-amps, digital logic and the basics of communication.",
    "chapters": [
        chapter("Semiconductor Diodes and Applications",
                ["Intrinsic and extrinsic semiconductors", "PN junction diode and V-I characteristics", "Half-wave and full-wave rectifiers", "Filters", "Zener diode as voltage regulator", "LED and photodiode"],
                "A PN junction conducts easily in forward bias and blocks in reverse bias, which makes it useful for rectifying AC into DC. A Zener diode holds a nearly constant voltage in reverse breakdown and is used for regulation.",
                ["Doping with pentavalent atoms gives n-type; trivalent atoms give p-type material.",
                 "Silicon diode starts conducting at about 0.7 V; germanium at about 0.3 V.",
                 "Full-wave rectifier has twice the DC output and lower ripple than half-wave.",
                 "A capacitor filter smooths the pulsating DC.",
                 "Zener works in reverse breakdown; series resistor limits current."],
                ["Half-wave: Vdc = Vm/pi, ripple factor = 1.21, efficiency = 40.6%", "Full-wave: Vdc = 2 Vm/pi, ripple factor = 0.48, efficiency = 81.2%", "PIV: half-wave = Vm; centre-tap full-wave = 2 Vm; bridge = Vm"],
                [S("What is the depletion region?"), S("Define ripple factor and rectification efficiency."), S("What is Zener breakdown?"),
                 L("Explain the V-I characteristics of a PN junction diode."), L("Explain the working of a full-wave bridge rectifier with waveforms."),
                 L("Explain how a Zener diode works as a voltage regulator."),
                 N("A half-wave rectifier has peak input 20 V. Find the average DC output voltage.", "Vdc = Vm/pi = 20/3.14 = 6.37 V (ignoring diode drop).")]),
        chapter("Bipolar Junction Transistor and Amplifiers",
                ["Construction of NPN and PNP transistors", "Transistor action", "CB, CE and CC configurations", "Input and output characteristics", "Transistor as a switch and as an amplifier", "Biasing (introduction)"],
                "A BJT is a current-controlled device with emitter, base and collector. A small base current controls a much larger collector current, so it can switch or amplify signals.",
                ["For normal operation the emitter-base junction is forward biased and the collector-base junction is reverse biased.",
                 "Common-emitter is the most used amplifier configuration, with high voltage and current gain and 180 degree phase shift.",
                 "In saturation the transistor acts as a closed switch; in cut-off as an open switch.",
                 "Biasing fixes the operating point (Q-point) for faithful amplification."],
                ["IE = IB + IC", "alpha = IC/IE,   beta = IC/IB,   beta = alpha/(1 - alpha)"],
                [S("Define alpha and beta of a transistor and state their relation."), S("Why is the base made thin and lightly doped?"), S("What is the Q-point?"),
                 L("Explain the input and output characteristics of a transistor in common-emitter configuration."), L("Explain how a transistor works as a switch."),
                 L("Compare CB, CE and CC configurations."),
                 N("A transistor has beta = 100 and base current 20 microamp. Find IC and IE.", "IC = 100 x 20 uA = 2 mA; IE = IB + IC = 2.02 mA.")]),
        chapter("Operational Amplifier",
                ["Ideal op-amp characteristics", "Virtual ground concept", "Inverting and non-inverting amplifiers", "Summing amplifier", "Integrator and differentiator", "Op-amp applications"],
                "An operational amplifier is a high-gain differential amplifier. With negative feedback its behaviour is set almost entirely by external resistors, which lets us build amplifiers, adders and integrators easily.",
                ["Ideal op-amp: infinite gain, infinite input impedance, zero output impedance.",
                 "With negative feedback the two input terminals are at nearly the same voltage (virtual short).",
                 "Inverting amplifier output is out of phase with input.",
                 "An integrator produces the integral of the input; a differentiator its derivative."],
                ["Inverting gain = -Rf/R1", "Non-inverting gain = 1 + Rf/R1", "Summer: Vo = -(Rf/R1 V1 + Rf/R2 V2)", "Integrator: Vo = -(1/RC) integral of Vin dt"],
                [S("List the characteristics of an ideal op-amp."), S("What is virtual ground?"), S("Draw a voltage follower and state its gain."),
                 L("Derive the gain of an inverting amplifier."), L("Explain the working of an op-amp integrator and differentiator."),
                 N("An inverting amplifier has R1 = 10 kilo-ohm and Rf = 100 kilo-ohm. Find the output for a 0.2 V input.", "Gain = -10; Vo = -2 V.")]),
        chapter("Digital Electronics",
                ["Number systems and conversions", "Logic gates and truth tables", "Boolean algebra and De Morgan's theorems", "Universal gates", "Half adder and full adder", "Flip-flops (introduction)"],
                "Digital circuits work with two levels, 0 and 1. Any logic function can be built from NAND or NOR gates, and adders are the building blocks of computer arithmetic.",
                ["NAND and NOR are universal gates.",
                 "De Morgan: (A.B)' = A' + B' and (A + B)' = A'.B'.",
                 "Half adder: Sum = A XOR B, Carry = A.B.",
                 "Full adder adds three bits (A, B and carry-in).",
                 "A flip-flop stores one bit of information."],
                ["Half adder: S = A xor B,  C = AB", "Full adder: S = A xor B xor Cin,  Cout = AB + Cin(A xor B)", "Binary to decimal: sum of bit x 2^position"],
                [S("Why are NAND and NOR called universal gates?"), S("State De Morgan's theorems."), S("Convert (1011)2 to decimal."),
                 L("Design a half adder and a full adder using logic gates."), L("Realise AND, OR and NOT gates using only NAND gates."),
                 L("Explain the working of an SR flip-flop."),
                 N("Convert decimal 45 to binary.", "45 = 101101 in binary.")]),
        chapter("Electronic Instruments and Communication Basics",
                ["Cathode ray oscilloscope (CRO)", "Digital multimeter", "Block diagram of a communication system", "Modulation: AM and FM", "Need of modulation", "Introduction to mobile and satellite communication"],
                "A CRO displays how a voltage changes with time and is the standard tool for measuring amplitude and frequency. Communication systems send information from a transmitter to a receiver through a channel using modulation.",
                ["CRO measures amplitude, time period and frequency of signals.",
                 "Modulation shifts the message signal to a higher carrier frequency for efficient radiation.",
                 "In AM the carrier amplitude varies with the message; in FM its frequency varies.",
                 "FM is less affected by noise than AM, but needs more bandwidth."],
                ["Modulation index (AM) = Em/Ec", "Frequency = 1/time period"],
                [S("Why is modulation needed?"), S("What is the modulation index?"), S("Differentiate between AM and FM."),
                 L("Explain the block diagram of a communication system."), L("Explain the working of a cathode ray oscilloscope with a block diagram."),
                 N("A CRO shows one full cycle over 4 divisions with 2 ms/div. Find the frequency.", "T = 8 ms; f = 1/0.008 = 125 Hz.")]),
    ],
}

PPS = {
    "slug": "bcs101", "codes": "BCS101 / BCS201", "name": "Programming for Problem Solving", "category": "Engineering Science",
    "credits": 3, "ltp": "2-1-0", "semester_group": "Sem 1 or Sem 2 (Programming / Mechanical group)",
    "syllabus_status": "outline", "status_note": OUTLINE_NOTE,
    "about": "Learn to think in algorithms and write programs in C: the base for every later programming course.",
    "chapters": [
        chapter("Introduction to Programming and C Basics",
                ["Components of a computer system", "Algorithms and flowcharts", "Structure of a C program", "Data types, variables and constants", "Operators and expressions", "Input and output functions"],
                "Programming means giving the computer a precise step-by-step solution. A C program has a main function, uses variables of different data types, and takes input and prints output using scanf and printf.",
                ["An algorithm is a finite, unambiguous sequence of steps; a flowchart is its diagram.",
                 "Common data types: int, float, double, char.",
                 "Operator precedence decides order of evaluation; use brackets to be clear.",
                 "Every statement ends with a semicolon.",
                 "Use %d for int, %f for float, %c for char, %s for string."],
                ["int main() { printf(\"Hello\"); return 0; }   (add #include <stdio.h> at the top)", "scanf(\"%d\", &n);   printf(\"%d\", n);", "Swap without third variable: a = a + b; b = a - b; a = a - b;"],
                [S("What is an algorithm? List its characteristics."), S("Differentiate between a compiler and an interpreter."), S("What are the basic data types in C?"),
                 L("Explain the structure of a C program with an example."), L("Explain the operators in C with examples."),
                 N("Write a C program to swap two numbers using a third variable.", "temp = a; a = b; b = temp;"),
                 N("Write a C program to find the area and circumference of a circle.", "area = 3.14159 * r * r; circumference = 2 * 3.14159 * r;")]),
        chapter("Control Statements and Loops",
                ["if, if-else, nested if, else-if ladder", "switch statement", "while, do-while and for loops", "break and continue", "Nested loops and patterns"],
                "Control statements let a program decide and repeat. if-else chooses between paths, switch picks one of many cases and loops repeat a block while a condition is true.",
                ["while checks the condition first; do-while runs the body at least once.",
                 "switch works with integer or character values and needs break to avoid fall-through.",
                 "break leaves the loop; continue skips to the next iteration.",
                 "Nested loops are used for patterns, tables and matrices."],
                ["if (cond) { ... } else { ... }", "for (i = 1; i <= n; i++) { ... }", "while (cond) { ... }   do { ... } while (cond);"],
                [S("Differentiate between while and do-while loops."), S("What is the use of break and continue?"), S("Why is break used in switch?"),
                 L("Explain if-else and switch statements with examples."), L("Explain the different loops in C with syntax and example."),
                 N("Write a C program to check whether a number is prime.", "Divide by 2 up to n/2 (or sqrt(n)); if any divisor is found it is not prime."),
                 N("Write a C program to print the Fibonacci series up to n terms.", "Start with a = 0, b = 1; next = a + b; shift a and b."),
                 N("Write a C program to print a right-angled star pattern.", "Outer loop for rows, inner loop prints i stars.")]),
        chapter("Arrays, Strings and Basic Algorithms",
                ["One-dimensional and two-dimensional arrays", "Matrix operations", "Strings and string functions", "Linear and binary search", "Bubble sort and selection sort"],
                "An array stores many values of the same type under one name, accessed by index starting from 0. Strings are character arrays ending with a null character. Searching and sorting are the first standard algorithms every programmer learns.",
                ["Array indices run from 0 to size - 1; going outside is undefined behaviour.",
                 "A string must end with '\\0'; use strlen, strcpy, strcmp, strcat from string.h.",
                 "Binary search needs a sorted array and takes O(log n) time; linear search takes O(n).",
                 "Bubble sort repeatedly swaps adjacent out-of-order elements; it takes O(n^2) time."],
                ["int a[5] = {1, 2, 3, 4, 5};", "int m[3][3];  m[i][j]", "char s[20];  strlen(s);  strcmp(s1, s2);"],
                [S("What is an array? How is it declared?"), S("Differentiate between linear search and binary search."), S("What is the role of the null character in strings?"),
                 L("Explain one-dimensional and two-dimensional arrays with examples."), L("Explain the bubble sort algorithm with an example."),
                 N("Write a C program to add two 3 x 3 matrices.", "Use two nested loops: c[i][j] = a[i][j] + b[i][j]."),
                 N("Write a C program to check whether a string is a palindrome.", "Compare s[i] with s[len - 1 - i] for half of the length."),
                 N("Write a C program for binary search.", "Keep low, high and mid; compare a[mid] with the key and shrink the range.")]),
        chapter("Functions and Recursion",
                ["Function declaration, definition and call", "Call by value and call by reference", "Recursion", "Storage classes: auto, static, extern, register", "Passing arrays to functions"],
                "A function packages a task so it can be reused. Recursion is when a function calls itself with a smaller problem until a base case is reached.",
                ["Call by value passes a copy; call by reference (using pointers) passes the address, so the function can change the original.",
                 "A recursive function needs a base case, otherwise it never stops.",
                 "static variables keep their value between calls.",
                 "Arrays are always passed by address."],
                ["int add(int a, int b) { return a + b; }", "Factorial: int f(int n) { if (n <= 1) return 1; return n * f(n - 1); }", "void swap(int *a, int *b) { int t = *a; *a = *b; *b = t; }"],
                [S("Differentiate between call by value and call by reference."), S("What is recursion? What is a base case?"), S("What is the use of the static storage class?"),
                 L("Explain the types of functions in C with examples."), L("Explain recursion with an example and compare it with iteration."),
                 N("Write a C program to find the factorial of a number using recursion.", "f(n) = n x f(n - 1) with f(0) = f(1) = 1."),
                 N("Write a C program to find the GCD of two numbers using a function.", "Euclid: gcd(a, b) = gcd(b, a % b) until b is 0."),
                 N("Write a C function to swap two numbers using call by reference.", "Pass addresses and swap through pointers.")]),
        chapter("Pointers, Structures and File Handling",
                ["Pointers and pointer arithmetic", "Pointers and arrays", "Dynamic memory allocation", "Structures and unions", "File handling: fopen, fclose, fprintf, fscanf", "Preprocessor directives"],
                "A pointer stores the address of a variable. A structure groups variables of different types under one name, and file handling lets a program store data permanently on disk.",
                ["& gives the address of a variable; * accesses the value at an address.",
                 "malloc and free manage heap memory; always free what you allocate.",
                 "A structure allocates memory for all members; a union shares the same memory among its members.",
                 "Always check that fopen returned a non-NULL pointer.",
                 "#include and #define are processed before compilation."],
                ["int *p = &x;   *p = 10;", "struct student { int roll; char name[20]; float marks; };", "FILE *fp = fopen(\"data.txt\", \"w\");  fprintf(fp, \"%d\", n);  fclose(fp);"],
                [S("What is a pointer? How is it declared?"), S("Differentiate between a structure and a union."), S("What is the difference between malloc and calloc?"),
                 L("Explain pointers and pointer arithmetic with examples."), L("Explain file operations in C with a suitable program."),
                 N("Write a C program to store and display details of n students using structures.", "Declare an array of struct student and use a loop for input and output."),
                 N("Write a C program to write text to a file and read it back.", "Use fopen with \"w\", then fopen with \"r\"; check for NULL."),
                 N("Write a C program to reverse an array using pointers.", "Use two pointers, one at each end, and swap while start < end.")]),
    ],
}

MECHANICAL = {
    "slug": "bme101", "codes": "BME101 / BME201", "name": "Fundamentals of Mechanical Engineering", "category": "Engineering Science",
    "credits": 3, "ltp": "2-1-0", "semester_group": "Sem 1 or Sem 2 (Programming / Mechanical group)",
    "syllabus_status": "outline", "status_note": OUTLINE_NOTE,
    "about": "Thermodynamics, engines, refrigeration, materials, manufacturing and the basics of stress and strain.",
    "chapters": [
        chapter("Basics of Thermodynamics",
                ["System, surroundings and properties", "Zeroth, first and second laws", "Heat, work and internal energy", "Kelvin-Planck and Clausius statements", "Carnot cycle and efficiency", "Entropy (introduction)"],
                "Thermodynamics studies energy transformations. The first law says energy is conserved, and the second law says heat cannot be fully converted into work, which limits the efficiency of every heat engine.",
                ["Open, closed and isolated systems differ in exchange of mass and energy.",
                 "First law: Q = delta-U + W.",
                 "Kelvin-Planck: no engine can convert all heat from a single reservoir into work.",
                 "Clausius: heat does not flow from cold to hot by itself without external work.",
                 "Carnot engine is the most efficient engine between two temperatures."],
                ["Q = dU + W", "Carnot efficiency = 1 - T2/T1 (temperatures in kelvin)", "Ideal gas: p V = m R T"],
                [S("State the zeroth law of thermodynamics."), S("Differentiate between open, closed and isolated systems."), S("State the Kelvin-Planck and Clausius statements."),
                 L("State the first law of thermodynamics and apply it to a closed system."), L("Explain the Carnot cycle with p-V diagram and derive its efficiency."),
                 N("A Carnot engine works between 600 K and 300 K. Find its efficiency.", "eta = 1 - 300/600 = 0.5 (50%)."),
                 N("A system receives 500 kJ of heat and does 200 kJ of work. Find the change in internal energy.", "dU = Q - W = 300 kJ.")]),
        chapter("Steam and Boilers",
                ["Properties of steam: dryness fraction, enthalpy", "Steam generation at constant pressure", "Boilers: classification, Cochran and Babcock-Wilcox", "Boiler mountings and accessories", "Steam turbines (introduction)"],
                "Steam is the working fluid in many power plants. A boiler generates steam by transferring heat from fuel to water, and mountings such as safety valves and gauges keep operation safe.",
                ["Dryness fraction x = mass of dry steam / total mass of mixture.",
                 "Fire-tube boilers (Cochran) are compact for low pressure; water-tube boilers (Babcock-Wilcox) suit high pressure.",
                 "Mountings are essential for safety (safety valve, pressure gauge, water level indicator).",
                 "Accessories improve efficiency (economiser, superheater, air pre-heater)."],
                ["Enthalpy of wet steam: h = hf + x hfg", "Boiler efficiency = heat used for steam / heat supplied by fuel"],
                [S("Define dryness fraction."), S("Differentiate between fire-tube and water-tube boilers."), S("List the boiler mountings."),
                 L("Explain the working of a Babcock-Wilcox boiler."), L("Explain the formation of steam at constant pressure with a temperature-enthalpy diagram."),
                 N("Find the enthalpy of 1 kg of wet steam with dryness fraction 0.9 if hf = 800 kJ/kg and hfg = 1900 kJ/kg.", "h = 800 + 0.9 x 1900 = 2510 kJ/kg.")]),
        chapter("Internal Combustion Engines",
                ["Classification of IC engines", "Four-stroke and two-stroke engines", "Petrol (SI) and diesel (CI) engines", "Otto and Diesel cycles", "Engine terms: bore, stroke, compression ratio", "Performance: indicated and brake power"],
                "An IC engine burns fuel inside the cylinder to produce power. The four-stroke cycle has suction, compression, power and exhaust strokes, and the theoretical cycles are Otto for petrol and Diesel for diesel engines.",
                ["Four-stroke engine gives one power stroke every two revolutions; two-stroke every revolution.",
                 "Petrol engine uses spark ignition; diesel engine uses compression ignition.",
                 "Compression ratio = total cylinder volume / clearance volume.",
                 "Otto efficiency increases with compression ratio.",
                 "Brake power is the useful power at the shaft; indicated power is the power developed in the cylinder."],
                ["Otto efficiency = 1 - 1/r^(gamma - 1)", "Compression ratio r = (Vs + Vc)/Vc", "Brake power = 2 pi N T / 60"],
                [S("Define compression ratio."), S("Differentiate between SI and CI engines."), S("What is the difference between two-stroke and four-stroke engines?"),
                 L("Explain the working of a four-stroke petrol engine with neat diagrams."), L("Explain the Otto cycle with p-V and T-s diagrams."),
                 N("Find the air-standard efficiency of an Otto cycle with compression ratio 8 (gamma = 1.4).", "eta = 1 - 8^(-0.4) = 0.565 (56.5%)."),
                 N("An engine develops torque of 100 N-m at 3000 rpm. Find the brake power.", "BP = 2 pi x 3000 x 100/60 = 31.4 kW.")]),
        chapter("Refrigeration and Air Conditioning",
                ["Refrigeration effect and unit (ton)", "Vapour compression refrigeration cycle", "Components of a refrigerator", "Refrigerants", "COP", "Window and split air conditioners (introduction)"],
                "A refrigerator moves heat from a cold space to a warm surroundings using work input. The vapour compression system uses a compressor, condenser, expansion valve and evaporator in a closed loop.",
                ["Evaporator absorbs heat from the cold space; condenser rejects heat to the surroundings.",
                 "COP = refrigeration effect / work input; it can be greater than 1.",
                 "One ton of refrigeration = 3.5 kW (approximately).",
                 "A good refrigerant has high latent heat, low freezing point and is non-toxic and eco-friendly."],
                ["COP = Q2/W = T2/(T1 - T2) for ideal refrigerator", "1 TR is about 3.5 kW"],
                [S("Define COP of a refrigerator."), S("What is one ton of refrigeration?"), S("Name the four main components of a vapour compression system."),
                 L("Explain the vapour compression refrigeration cycle with a neat diagram."), L("Explain the working of a window air conditioner."),
                 N("A refrigerator works between -10 C and 30 C. Find the ideal COP.", "T2 = 263 K, T1 = 303 K; COP = 263/40 = 6.58.")]),
        chapter("Engineering Materials and Manufacturing Processes",
                ["Classification of engineering materials", "Mechanical properties: strength, hardness, ductility, toughness", "Casting", "Welding: arc and gas", "Forging and rolling", "Machining: lathe, drilling, milling"],
                "Materials are chosen by their properties, and manufacturing processes give them the required shape. Casting pours molten metal into moulds, welding joins metals, and machining removes material to reach accurate dimensions.",
                ["Ductile materials can be drawn into wires; brittle materials fracture with little deformation.",
                 "Casting is used for complex shapes; forging improves strength by refining grain structure.",
                 "Arc welding uses an electric arc to melt and fuse metals.",
                 "Lathe produces cylindrical parts; drilling makes holes; milling cuts flat or shaped surfaces."],
                ["Cutting speed v = pi D N / 1000 m/min (D in mm, N in rpm)"],
                [S("Differentiate between ductility and malleability."), S("What is casting? Name two casting defects."), S("Name four operations performed on a lathe."),
                 L("Explain the sand casting process with a neat diagram."), L("Explain arc welding and gas welding."),
                 N("Find the cutting speed for a 50 mm diameter job at 400 rpm.", "v = pi x 50 x 400/1000 = 62.8 m/min.")]),
        chapter("Stress, Strain and Power Transmission",
                ["Stress and strain", "Hooke's law and elastic constants", "Stress-strain curve of mild steel", "Types of beams and loads (introduction)", "Belt and gear drives (introduction)"],
                "Stress is internal resistance per unit area, strain is the relative change in length. Within the elastic limit stress is proportional to strain. Belts and gears transmit power between shafts.",
                ["Normal stress = force/area; strain has no unit.",
                 "Young's modulus E = stress/strain in the elastic region.",
                 "Mild steel shows an elastic limit, yield point, ultimate strength and fracture point.",
                 "Factor of safety = ultimate stress / working stress.",
                 "Gear drives give positive drive without slip; belt drives may slip."],
                ["sigma = F/A,   epsilon = dL/L,   E = sigma/epsilon", "Velocity ratio of gears = N1/N2 = T2/T1"],
                [S("State Hooke's law."), S("Define factor of safety."), S("Differentiate between belt and gear drives."),
                 L("Draw and explain the stress-strain curve of mild steel."), L("Explain different types of beams and loads."),
                 N("A steel rod of 10 mm diameter carries a tensile load of 15.7 kN. Find the stress.", "A = pi/4 x 100 = 78.5 mm^2; sigma = 15700/78.5 = 200 MPa.")]),
    ],
}


# Mechanical has six topic groups here; the Study Hub uses five units, so the last two are shown together.
MECHANICAL["chapters"] = MECHANICAL["chapters"][:4] + [
    merge_chapters(MECHANICAL["chapters"][4], MECHANICAL["chapters"][5], "Materials, Manufacturing, Stress and Strain")]

SUBJECTS = [
    to_subject(ELECTRICAL, ["Basic Electrical Engineering - V.N. Mittle & Arvind Mittal (McGraw-Hill)", "A Textbook of Electrical Technology - B.L. Theraja (S. Chand)"]),
    to_subject(ELECTRONICS, ["Electronic Devices and Circuit Theory - Boylestad & Nashelsky (Pearson)", "Digital Design - M. Morris Mano (Pearson)"]),
    to_subject(PPS, ["Let Us C - Yashavant Kanetkar (BPB)", "Programming in ANSI C - E. Balagurusamy (McGraw-Hill)", "The C Programming Language - Kernighan & Ritchie (Pearson)"],
               code_reference=True),
    to_subject(MECHANICAL, ["Basic Mechanical Engineering - Pravin Kumar (Pearson)", "Engineering Thermodynamics - P.K. Nag (McGraw-Hill)"]),
]
