"""AKTU 1st year - Engineering Mathematics-I (BAS103) and Engineering Mathematics-II (BAS203)."""
from database.aktu_helpers import L, N, S, chapter, to_subject

MATHS1 = {
    "slug": "bas103", "codes": "BAS103", "name": "Engineering Mathematics-I", "category": "Mathematics",
    "credits": 4, "ltp": "3-1-0", "semester_group": "Sem 1",
    "syllabus_status": "matched",
    "status_note": "Chapter titles match the published AKTU unit titles for BAS103 (Matrices, Differential Calculus I and II, Multiple Integration, Vector Calculus). Check the topic details against your session's PDF.",
    "about": "Matrices, calculus of several variables, multiple integrals and vector calculus: the maths toolkit for all branches.",
    "chapters": [
        chapter("Matrices",
                ["Hermitian, skew-Hermitian and unitary matrices", "Rank of a matrix (echelon and normal form)", "Consistency of linear equations", "Eigenvalues and eigenvectors", "Cayley-Hamilton theorem", "Inverse using Cayley-Hamilton", "Diagonalisation", "Engineering applications"],
                "Matrices let us write and solve systems of linear equations compactly. Rank decides whether a system has no, one or infinitely many solutions, and eigenvalues describe how a matrix stretches vectors. The Cayley-Hamilton theorem says every square matrix satisfies its own characteristic equation.",
                ["A system AX = B is consistent if rank(A) = rank([A|B]); unique solution if this rank equals the number of unknowns.",
                 "Sum of eigenvalues = trace; product of eigenvalues = determinant.",
                 "Eigenvalues of a Hermitian matrix are real; of a skew-Hermitian matrix purely imaginary or zero; of a unitary matrix have modulus 1.",
                 "Cayley-Hamilton lets you find the inverse and higher powers of a matrix.",
                 "A matrix is diagonalisable if it has n linearly independent eigenvectors."],
                ["Characteristic equation: |A - lambda I| = 0", "Consistency: rank A = rank [A|B]", "If A^2 - 5A + 6I = 0 then A^-1 = (5I - A)/6", "Diagonalisation: P^-1 A P = D"],
                [S("Define Hermitian, skew-Hermitian and unitary matrices with one example each."), S("State the Cayley-Hamilton theorem."), S("Write the condition for consistency of a system of linear equations."),
                 L("Find the rank of a given matrix by reducing it to echelon form and discuss the consistency of a system."),
                 L("Find the eigenvalues and eigenvectors of a 3 x 3 matrix.", "Solve |A - lambda I| = 0, then solve (A - lambda I)X = 0 for each lambda."),
                 L("Verify the Cayley-Hamilton theorem for a given matrix and use it to find its inverse."),
                 L("Diagonalise a given matrix and find A^5."),
                 N("Find the eigenvalues of the matrix [[1, 2], [2, 1]].", "lambda^2 - 2 lambda - 3 = 0, so lambda = 3 and -1.")]),
        chapter("Differential Calculus - I",
                ["Successive differentiation and Leibnitz theorem", "Partial differentiation", "Euler's theorem on homogeneous functions", "Total derivative", "Change of variables", "Taylor's and Maclaurin's series"],
                "This chapter extends differentiation to higher orders and to functions of several variables. Euler's theorem gives a neat identity for homogeneous functions, and Taylor and Maclaurin series approximate functions by polynomials.",
                ["Leibnitz theorem gives the nth derivative of a product of two functions.",
                 "For a homogeneous function u of degree n: x u_x + y u_y = n u.",
                 "Total derivative: du/dt = u_x dx/dt + u_y dy/dt.",
                 "Maclaurin series is Taylor series about x = 0.",
                 "Standard expansions: e^x, sin x, cos x, log(1+x)."],
                ["(uv)n = sum of nCr u(n-r) v(r)", "Euler: x du/dx + y du/dy = n u", "Taylor: f(x) = f(a) + (x-a) f'(a) + (x-a)^2/2! f''(a) + ...", "Maclaurin: f(x) = f(0) + x f'(0) + x^2/2! f''(0) + ..."],
                [S("State Leibnitz theorem."), S("State Euler's theorem on homogeneous functions."), S("Write the Maclaurin series of e^x."),
                 L("If y = sin(m sin^-1 x), prove (1 - x^2) y2 - x y1 + m^2 y = 0 and find the nth derivative at x = 0.", "Differentiate twice, then differentiate n times using Leibnitz theorem."),
                 L("If u = f(y/x), prove that x u_x + y u_y = 0."),
                 L("Expand log(1 + x) in powers of x using Maclaurin's series."),
                 L("Expand sin x in powers of (x - pi/2) using Taylor's series."),
                 N("If u = x^2 y + y^2 z + z^2 x, find x u_x + y u_y + z u_z.", "u is homogeneous of degree 3, so the result is 3u.")]),
        chapter("Differential Calculus - II",
                ["Jacobians", "Approximation of errors", "Maxima and minima of functions of two variables", "Lagrange's method of undetermined multipliers"],
                "Jacobians describe how a change of variables scales area or volume. Maxima and minima of functions of two variables are found by solving f_x = f_y = 0 and applying a second-derivative test, and Lagrange multipliers handle constrained optimisation.",
                ["Jacobian J = d(u,v)/d(x,y) is the determinant of partial derivatives; J x J' = 1 for inverse transformations.",
                 "Stationary points satisfy f_x = 0 and f_y = 0.",
                 "With r = f_xx, s = f_xy, t = f_yy: if rt - s^2 > 0 and r < 0 it is a maximum; if rt - s^2 > 0 and r > 0 a minimum; if rt - s^2 < 0 a saddle point.",
                 "Lagrange: to optimise f subject to phi = 0, solve grad f = lambda grad phi."],
                ["J = d(u,v)/d(x,y) = |u_x u_y; v_x v_y|", "Error: delta-f ~ f_x delta-x + f_y delta-y", "Max/min test: rt - s^2 and r", "Lagrange function: F = f + lambda phi"],
                [S("Define the Jacobian. Write its use in a change of variables."), S("What is a saddle point?"), S("State the condition for a maximum of f(x, y)."),
                 L("Find the maxima and minima of f(x, y) = x^3 + y^3 - 3axy."),
                 L("Find the minimum value of x^2 + y^2 + z^2 subject to x + y + z = 3a using Lagrange multipliers."),
                 L("If x = r cos(theta), y = r sin(theta), find d(x,y)/d(r,theta)."),
                 N("The radius and height of a cone are measured as 5 cm and 12 cm with possible error 0.1 cm in each. Estimate the error in the volume.", "V = (1/3) pi r^2 h; dV = (pi/3)(2rh dr + r^2 dh) = (pi/3)(12 + 2.5) = 15.18 cm^3 approx (taking 0.1 cm errors).")]),
        chapter("Multiple Integration",
                ["Double integral and change of order", "Change of variables (polar coordinates)", "Triple integral", "Area and volume by integration", "Beta and Gamma functions", "Dirichlet's integral"],
                "Multiple integrals add up quantities over areas and volumes. Changing the order of integration or switching to polar coordinates often makes a hard integral easy, and Beta and Gamma functions evaluate many standard integrals quickly.",
                ["Reverse the order of integration by sketching the region and re-describing the limits.",
                 "Use polar form x = r cos(theta), y = r sin(theta), dA = r dr d(theta) for circular regions.",
                 "Gamma function: Gamma(n+1) = n Gamma(n); Gamma(1/2) = sqrt(pi).",
                 "Beta and Gamma are connected: B(m, n) = Gamma(m) Gamma(n)/Gamma(m+n).",
                 "Area = double integral of dx dy; volume = triple integral of dx dy dz."],
                ["Gamma(n) = integral of e^-x x^(n-1) dx from 0 to infinity", "B(m,n) = 2 integral of sin^(2m-1)(t) cos^(2n-1)(t) dt, 0 to pi/2", "integral of sin^p cos^q from 0 to pi/2 = (1/2) B((p+1)/2, (q+1)/2)", "Polar: dA = r dr d(theta)"],
                [S("State the relation between Beta and Gamma functions."), S("What is Gamma(1/2)?"), S("Write the formula for area in polar coordinates."),
                 L("Change the order of integration and evaluate a given double integral.", "Sketch the region first, then swap the limits."),
                 L("Evaluate the double integral over the first quadrant of x y dx dy within the circle x^2 + y^2 = a^2."),
                 L("Find the volume of the sphere x^2 + y^2 + z^2 = a^2 using triple integration."),
                 L("Evaluate integral of sin^4(x) cos^3(x) from 0 to pi/2 using the Beta function."),
                 N("Evaluate Gamma(5/2).", "Gamma(5/2) = (3/2)(1/2) Gamma(1/2) = (3/4) sqrt(pi).")]),
        chapter("Vector Calculus",
                ["Gradient, divergence and curl", "Directional derivative", "Line, surface and volume integrals", "Green's theorem", "Stokes' theorem", "Gauss divergence theorem"],
                "Vector calculus describes fields such as velocity, force and electric fields. Gradient gives the direction of steepest increase of a scalar, divergence measures outflow, and curl measures rotation. Green, Stokes and Gauss convert between line, surface and volume integrals.",
                ["Gradient of a scalar is a vector normal to the level surface; the directional derivative is grad f . unit vector.",
                 "A field is irrotational if curl F = 0 and solenoidal if div F = 0.",
                 "Green's theorem links a line integral around a plane curve to a double integral over the region.",
                 "Stokes: circulation around a closed curve = flux of curl through a surface bounded by it.",
                 "Gauss: outward flux through a closed surface = triple integral of divergence."],
                ["grad f = (f_x, f_y, f_z)", "div F = d(F1)/dx + d(F2)/dy + d(F3)/dz", "Green: closed integral of (P dx + Q dy) = double integral of (Q_x - P_y) dx dy", "Stokes: closed integral of F . dr = double integral of (curl F) . n dS", "Gauss: closed surface integral of F . n dS = triple integral of div F dV"],
                [S("Define gradient, divergence and curl."), S("What is an irrotational field?"), S("State Gauss divergence theorem."),
                 L("Verify Green's theorem for a given integral over a closed curve."),
                 L("Verify Stokes' theorem for a given vector field over a given surface."),
                 L("Verify the Gauss divergence theorem for a given field over a cube."),
                 N("Find the directional derivative of f = x^2 + y^2 + z^2 at (1, 1, 1) in the direction (1, 2, 2).", "grad f = (2, 2, 2); unit vector = (1, 2, 2)/3; result = (2 + 4 + 4)/3 = 10/3."),
                 N("Show that F = (y + z, z + x, x + y) is irrotational.", "Compute curl F; every component is zero.")]),
    ],
}

MATHS2 = {
    "slug": "bas203", "codes": "BAS203", "name": "Engineering Mathematics-II", "category": "Mathematics",
    "credits": 4, "ltp": "3-1-0", "semester_group": "Sem 2",
    "syllabus_status": "outline",
    "status_note": "Chapter outline built from the standard topics of Engineering Mathematics-II (differential equations, Laplace transforms, series and PDE basics). The unit order and exact content may differ in your session's official syllabus, so compare with the PDF.",
    "about": "Differential equations and transforms: the language of circuits, vibrations and heat.",
    "chapters": [
        chapter("Ordinary Differential Equations of First Order",
                ["Variable separable", "Homogeneous equations", "Exact equations and integrating factors", "Linear equations", "Bernoulli's equation", "Orthogonal trajectories and applications"],
                "A first-order differential equation relates a function to its first derivative. Each type has a standard method: separate the variables, use a substitution, find an integrating factor or reduce to a linear form.",
                ["M dx + N dy = 0 is exact if dM/dy = dN/dx.",
                 "Linear form dy/dx + P y = Q has integrating factor e^(integral of P dx).",
                 "Bernoulli's equation dy/dx + P y = Q y^n becomes linear on substituting v = y^(1-n).",
                 "Homogeneous equations are solved with y = vx.",
                 "Applications: Newton's law of cooling, growth and decay, orthogonal trajectories."],
                ["Exactness: dM/dy = dN/dx", "Linear: y e^(int P dx) = int Q e^(int P dx) dx + C", "Bernoulli: v = y^(1-n)"],
                [S("When is M dx + N dy = 0 exact?"), S("Write the integrating factor of a linear differential equation."), S("What are orthogonal trajectories?"),
                 L("Solve dy/dx + y/x = x^2 and state the method."), L("Solve the exact equation (2xy + 1) dx + (x^2 + 4y) dy = 0."),
                 L("Solve the Bernoulli equation dy/dx + y = x y^3."), L("Find the orthogonal trajectories of the family of curves y = c x^2."),
                 N("A body at 100 C cools to 80 C in 10 minutes in air at 30 C. Find its temperature after 20 minutes.", "T - 30 = 70 e^(-kt); 50 = 70 e^(-10k); at t = 20 T = 30 + 70 (5/7)^2 = 65.7 C.")]),
        chapter("Linear Differential Equations of Higher Order",
                ["Complementary function and particular integral", "Operator D method", "Cauchy-Euler equation", "Legendre's linear equation", "Method of variation of parameters", "Applications to mechanical and electrical systems"],
                "A linear equation with constant coefficients has a general solution y = complementary function + particular integral. The complementary function comes from the roots of the auxiliary equation, and the particular integral from a method suited to the right-hand side.",
                ["Real distinct roots give e^(m x) terms; repeated roots add a factor x; complex roots a +/- i b give e^(a x)(cos bx, sin bx).",
                 "Cauchy-Euler equation is reduced to constant coefficients with x = e^z.",
                 "Variation of parameters works for any right-hand side once the CF is known.",
                 "Spring-mass and LCR circuits give second-order equations."],
                ["Auxiliary equation: a m^2 + b m + c = 0", "PI of e^(ax): e^(ax)/f(a) if f(a) is not 0", "Variation of parameters: u = -integral of y2 R/W, v = integral of y1 R/W", "Cauchy-Euler: x = e^z"],
                [S("Write the general solution when the auxiliary equation has complex roots."), S("What is the Wronskian?"), S("What substitution reduces a Cauchy-Euler equation to constant coefficients?"),
                 L("Solve (D^2 - 3D + 2) y = e^(3x)."), L("Solve (D^2 + 4) y = sin 2x."),
                 L("Solve x^2 y'' - x y' + y = log x."), L("Solve y'' + y = sec x by variation of parameters."),
                 N("Solve y'' - 5y' + 6y = 0 with y(0) = 1 and y'(0) = 0.", "m = 2, 3; y = A e^(2x) + B e^(3x); A + B = 1 and 2A + 3B = 0 so A = 3, B = -2.")]),
        chapter("Series Solutions and Special Functions",
                ["Power series method", "Frobenius method (introduction)", "Legendre's equation and polynomials", "Bessel's equation (introduction)", "Orthogonality properties"],
                "When an equation has variable coefficients, we seek the solution as a power series. Legendre and Bessel equations are two famous cases that appear in physics and engineering problems with spherical and cylindrical symmetry.",
                ["Substitute y = sum a_n x^n and compare coefficients to get a recurrence relation.",
                 "Legendre polynomials: P0 = 1, P1 = x, P2 = (3x^2 - 1)/2.",
                 "Legendre polynomials are orthogonal on [-1, 1].",
                 "Bessel functions J_n(x) solve x^2 y'' + x y' + (x^2 - n^2) y = 0."],
                ["Legendre: (1 - x^2) y'' - 2x y' + n(n+1) y = 0", "Rodrigues: P_n(x) = (1/(2^n n!)) d^n/dx^n (x^2 - 1)^n", "Orthogonality: integral of P_m P_n dx = 0 for m not equal to n"],
                [S("Write Legendre's differential equation."), S("Write P2(x) of the Legendre polynomial."), S("What is an ordinary point of a differential equation?"),
                 L("Solve y'' + y = 0 by the power series method."), L("Obtain the series solution of Legendre's equation about x = 0."),
                 L("State and prove the orthogonality of Legendre polynomials (outline).")]),
        chapter("Laplace Transform",
                ["Definition and existence", "Laplace transforms of standard functions", "First shifting theorem", "Transforms of derivatives and integrals", "Unit step and Dirac delta function", "Inverse Laplace transform and convolution theorem", "Solving differential equations"],
                "The Laplace transform converts a differential equation into an algebraic one, solves it in the s-domain, and converts back. It handles initial conditions automatically and works well with discontinuous inputs.",
                ["L{1} = 1/s, L{t^n} = n!/s^(n+1), L{e^(at)} = 1/(s - a).",
                 "L{sin at} = a/(s^2 + a^2), L{cos at} = s/(s^2 + a^2).",
                 "First shifting: L{e^(at) f(t)} = F(s - a).",
                 "L{f'} = s F(s) - f(0); L{f''} = s^2 F - s f(0) - f'(0).",
                 "Convolution theorem: inverse of F(s) G(s) = integral of f(u) g(t - u) du."],
                ["L{f(t)} = integral of e^(-st) f(t) dt from 0 to infinity", "L{t f(t)} = -F'(s)", "L{u(t - a)} = e^(-as)/s", "L{f'(t)} = s F(s) - f(0)"],
                [S("Define the Laplace transform."), S("State the first shifting theorem."), S("Find L{sin 3t}."),
                 L("Find the Laplace transform of t e^(2t) sin t."), L("State and prove the convolution theorem."),
                 L("Find the inverse Laplace transform of 1/((s + 1)(s^2 + 1))."),
                 L("Solve y'' + 4y = 0 with y(0) = 1 and y'(0) = 0 using Laplace transform."),
                 N("Find L{e^(3t) + 5 cos 2t}.", "1/(s - 3) + 5s/(s^2 + 4).")]),
        chapter("Fourier Series and Partial Differential Equations (basics)",
                ["Fourier series of periodic functions", "Even and odd functions", "Half-range series", "Formation of partial differential equations", "Lagrange's linear equation", "Method of separation of variables (introduction)"],
                "A periodic function can be written as a sum of sines and cosines. A partial differential equation involves partial derivatives of a function of several variables; simple ones are solved by Lagrange's method or by separation of variables.",
                ["For an even function only cosine terms appear; for an odd function only sine terms.",
                 "Fourier coefficients a0, an and bn are found by integrating over one period.",
                 "Formation of a PDE: eliminate arbitrary constants or functions.",
                 "Lagrange's equation P p + Q q = R has auxiliary equations dx/P = dy/Q = dz/R."],
                ["a0 = (1/L) int f dx, an = (1/L) int f cos(n pi x/L) dx, bn = (1/L) int f sin(n pi x/L) dx", "Lagrange: dx/P = dy/Q = dz/R"],
                [S("State Dirichlet's conditions."), S("Which terms vanish in the Fourier series of an odd function?"), S("Write Lagrange's linear PDE."),
                 L("Find the Fourier series of f(x) = x in (-pi, pi)."), L("Obtain the half-range sine series of f(x) = x in (0, pi)."),
                 L("Form the PDE by eliminating a and b from z = (x + a)(y + b)."), L("Solve y z p + z x q = x y.")]),
    ],
}


MATHS_BOOKS = ["Higher Engineering Mathematics - B.S. Grewal (Khanna Publishers)", "Advanced Engineering Mathematics - Erwin Kreyszig (Wiley)",
               "Advanced Engineering Mathematics - R.K. Jain & S.R.K. Iyengar (Narosa)"]
# BAS103 unit titles and the 8 hours per unit were cross-checked with published copies of the AKTU syllabus.
SUBJECTS = [to_subject(MATHS1, MATHS_BOOKS, hours=8), to_subject(MATHS2, MATHS_BOOKS)]
