"""AKTU 1st year - Environment and Ecology (BAS104/204) and Soft Skills (BAS105/205)."""
from database.aktu_helpers import L, N, S, chapter, to_subject

OUTLINE_NOTE = ("Chapter outline built from the standard topics of this course under AKTU. Unit titles and order can differ in your "
                "session's official syllabus, so compare with the PDF on aktu.ac.in.")

ENVIRONMENT = {
    "slug": "bas104", "codes": "BAS104 / BAS204", "name": "Environment and Ecology", "category": "Basic Science",
    "credits": 3, "ltp": "3-0-0", "semester_group": "Sem 1 or Sem 2 (Environment / Soft Skills group)",
    "syllabus_status": "outline", "status_note": OUTLINE_NOTE,
    "about": "How ecosystems work, how humans affect them, and the laws and practices that protect the environment.",
    "chapters": [
        chapter("Environment, Ecosystems and Natural Resources",
                ["Definition and scope of environment", "Structure and function of an ecosystem", "Food chain, food web and trophic levels", "Energy flow and ecological pyramids", "Ecological succession", "Renewable and non-renewable resources"],
                "An ecosystem is a community of living organisms interacting with their physical surroundings. Energy enters as sunlight, passes through producers, consumers and decomposers, and most of it is lost as heat at every step.",
                ["Producers (green plants) make food; consumers eat; decomposers recycle nutrients.",
                 "Only about 10% of energy passes from one trophic level to the next (Lindeman's 10% law).",
                 "Energy flow is one-way; nutrients cycle.",
                 "Ecological pyramids can be of number, biomass or energy; the energy pyramid is always upright.",
                 "Succession: gradual replacement of one community by another until a stable climax community forms."],
                ["Key fact: 10% energy transfer between trophic levels", "Biotic = living components; abiotic = air, water, soil, light, temperature"],
                [S("Define ecosystem. What are its components?"), S("State the 10% law of energy transfer."), S("Differentiate between a food chain and a food web."),
                 L("Explain the structure and functions of an ecosystem."), L("Explain energy flow in an ecosystem and ecological pyramids."),
                 L("Explain ecological succession with its stages."),
                 N("If producers fix 10,000 kJ of energy, how much reaches the secondary consumers by the 10% law?", "10,000 -> 1,000 (primary consumers) -> 100 kJ (secondary consumers).")]),
        chapter("Biodiversity and Conservation",
                ["Levels of biodiversity: genetic, species, ecosystem", "Value of biodiversity", "India as a mega-diversity nation", "Biodiversity hotspots", "Threats: habitat loss, poaching, man-wildlife conflict", "In-situ and ex-situ conservation"],
                "Biodiversity is the variety of life at gene, species and ecosystem levels. It provides food, medicine and ecological balance, but it is threatened by habitat destruction and over-exploitation, so it is protected through national parks, sanctuaries, seed banks and zoos.",
                ["India's biodiversity hotspots include the Himalaya, Indo-Burma, Western Ghats and Sri Lanka, and Sundaland (Nicobar Islands).",
                 "In-situ conservation protects species in their natural habitat (national parks, sanctuaries, biosphere reserves).",
                 "Ex-situ conservation protects them outside the habitat (zoos, botanical gardens, gene banks).",
                 "Habitat loss is the biggest threat to biodiversity.",
                 "Endangered species are listed in the IUCN Red Data Book."],
                ["Biodiversity types: genetic, species, ecosystem", "In-situ: national parks; Ex-situ: zoos, gene banks"],
                [S("What is a biodiversity hotspot?"), S("Differentiate between in-situ and ex-situ conservation."), S("Why is India called a mega-diversity country?"),
                 L("Explain the levels and values of biodiversity."), L("Discuss the threats to biodiversity and the methods of conservation."),
                 L("Write short notes on biosphere reserves and national parks.")]),
        chapter("Environmental Pollution and Waste Management",
                ["Air pollution: sources, effects, control", "Water pollution and treatment", "Soil pollution", "Noise and thermal pollution", "Solid waste management", "E-waste and hazardous waste", "Disaster management (introduction)"],
                "Pollution is the addition of harmful substances to air, water or soil. It harms health and ecosystems and is controlled through cleaner technology, treatment and the 3Rs: reduce, reuse and recycle.",
                ["Major air pollutants: SO2, NOx, CO, particulate matter and ozone.",
                 "BOD measures oxygen needed by microbes to break down organic matter in water; high BOD means polluted water.",
                 "Noise is measured in decibels (dB).",
                 "Segregation of waste at source is the first step of solid waste management.",
                 "E-waste contains toxic metals such as lead and mercury and should go to authorised recyclers."],
                ["Key fact: 3Rs = Reduce, Reuse, Recycle", "Noise unit = decibel (dB)"],
                [S("Define pollution and pollutant."), S("What is BOD?"), S("What is e-waste?"),
                 L("Explain the causes, effects and control of air pollution."), L("Explain the sources, effects and treatment of water pollution."),
                 L("Explain the methods of solid waste management."), L("Write short notes on noise pollution and thermal pollution.")]),
        chapter("Global Environmental Issues and Sustainable Development",
                ["Global warming and greenhouse effect", "Ozone layer depletion", "Acid rain", "Climate change", "Water conservation and rainwater harvesting", "Sustainable development", "Renewable energy"],
                "Human activities are changing the climate and damaging the ozone layer. Sustainable development meets present needs without harming the ability of future generations to meet theirs, and it relies on renewable energy and resource conservation.",
                ["Greenhouse gases include CO2, methane, nitrous oxide and water vapour.",
                 "CFCs destroy stratospheric ozone; the Montreal Protocol (1987) phases them out.",
                 "Acid rain is caused by SO2 and NOx and damages buildings, soil and lakes.",
                 "The Paris Agreement (2015) aims to limit global warming.",
                 "Rainwater harvesting recharges groundwater and reduces runoff."],
                ["Key fact: Montreal Protocol (1987) for ozone; Kyoto Protocol (1997) and Paris Agreement (2015) for climate"],
                [S("What is the greenhouse effect?"), S("What is acid rain?"), S("Define sustainable development."),
                 L("Explain global warming, its causes, effects and control measures."), L("Explain ozone layer depletion and its consequences."),
                 L("Discuss rainwater harvesting and water conservation methods.")]),
        chapter("Environmental Laws and Protection",
                ["Environment (Protection) Act, 1986", "Water Act, 1974 and Air Act, 1981", "Wildlife Protection Act, 1972", "Forest Conservation Act, 1980", "Environmental Impact Assessment (EIA)", "Environmental ethics and public awareness"],
                "India has several laws to protect the environment. Industries need clearance based on an Environmental Impact Assessment, and public awareness and ethics are essential for the laws to work.",
                ["Environment (Protection) Act, 1986 is the umbrella law passed after the Bhopal gas tragedy.",
                 "Water (Prevention and Control of Pollution) Act, 1974 and Air Act, 1981 set up pollution control boards.",
                 "Wildlife Protection Act, 1972 protects wild animals and their habitats.",
                 "Forest (Conservation) Act, 1980 restricts diversion of forest land for other uses.",
                 "EIA predicts the environmental effects of a project before it starts."],
                ["Key facts: Wildlife Act 1972, Water Act 1974, Forest Act 1980, Air Act 1981, EP Act 1986"],
                [S("What is EIA?"), S("Name the Acts passed for control of water and air pollution."), S("What is the purpose of the Wildlife Protection Act?"),
                 L("Explain the Environment (Protection) Act, 1986."), L("Explain the process and importance of Environmental Impact Assessment."),
                 L("Write a note on environmental ethics and the role of individuals in conservation.")]),
    ],
}

SOFT_SKILLS = {
    "slug": "bas105", "codes": "BAS105 / BAS205", "name": "Soft Skills", "category": "Humanities",
    "credits": 3, "ltp": "3-0-0", "semester_group": "Sem 1 or Sem 2 (Environment / Soft Skills group)",
    "syllabus_status": "outline", "status_note": OUTLINE_NOTE,
    "about": "Communication, teamwork, time management and interview skills that decide how far your technical skills can take you.",
    "chapters": [
        chapter("Soft Skills and Personality Development",
                ["Soft skills vs hard skills", "Self-awareness and SWOT analysis", "Attitude and positive thinking", "Goal setting (SMART goals)", "Emotional intelligence"],
                "Hard skills are job-specific technical abilities; soft skills are personal qualities such as communication, teamwork and adaptability. Knowing your strengths and weaknesses and setting clear goals are the first steps of personal growth.",
                ["SWOT: Strengths, Weaknesses, Opportunities, Threats.",
                 "SMART goals are Specific, Measurable, Achievable, Relevant and Time-bound.",
                 "A positive attitude improves performance and relationships.",
                 "Emotional intelligence means recognising and managing your own and others' emotions."],
                ["SMART = Specific, Measurable, Achievable, Relevant, Time-bound", "SWOT = Strengths, Weaknesses, Opportunities, Threats"],
                [S("Differentiate between hard skills and soft skills."), S("What is SWOT analysis?"), S("What are SMART goals?"),
                 L("Explain the importance of soft skills for engineers."), L("Explain self-awareness and how to build a positive attitude."),
                 L("What is emotional intelligence? Explain its components.")]),
        chapter("Communication Skills",
                ["Process of communication", "Verbal and non-verbal communication", "Body language", "Active listening", "Barriers to communication", "The 7 Cs of effective communication"],
                "Communication is the exchange of information between a sender and a receiver. It is effective when the message is understood as intended, and listening is as important as speaking.",
                ["Communication process: sender, message, channel, receiver, feedback.",
                 "Non-verbal signals include posture, eye contact, gestures and facial expression.",
                 "Barriers can be physical (noise), semantic (jargon), psychological or cultural.",
                 "7 Cs: clear, concise, concrete, correct, coherent, complete, courteous.",
                 "Active listening means giving full attention, not interrupting and giving feedback."],
                ["7 Cs = Clear, Concise, Concrete, Correct, Coherent, Complete, Courteous"],
                [S("Define communication. Name its elements."), S("What is non-verbal communication?"), S("List the 7 Cs of communication."),
                 L("Explain the process of communication with a diagram."), L("Discuss the barriers to communication and how to overcome them."),
                 L("Explain the role of body language in effective communication.")]),
        chapter("Interpersonal Skills and Teamwork",
                ["Teamwork and team roles", "Leadership qualities", "Conflict management", "Negotiation and persuasion", "Professional etiquette", "Empathy and respect for diversity"],
                "Engineers work in teams, so the ability to cooperate, lead and resolve conflict is essential. Good teams share goals, trust each other and communicate openly.",
                ["Tuckman's stages of a team: forming, storming, norming, performing.",
                 "A good leader inspires, listens and takes responsibility.",
                 "Conflicts should be handled by discussing the issue, not attacking the person.",
                 "Professional etiquette includes punctuality, polite language and respect for others' time."],
                ["Tuckman: Forming, Storming, Norming, Performing"],
                [S("What is teamwork? Why is it important?"), S("List four qualities of a good leader."), S("What are Tuckman's stages of team formation?"),
                 L("Explain the strategies for conflict management."), L("Explain the importance of etiquette in professional life."),
                 L("Discuss the role of empathy and diversity in a team.")]),
        chapter("Time and Stress Management",
                ["Importance of time management", "Prioritisation: urgent-important matrix", "Procrastination", "Causes and effects of stress", "Stress management techniques", "Work-life balance"],
                "Managing time means deciding what matters and doing it first. Stress is the body's response to pressure; a little stress helps performance, but too much harms health and can be reduced by planning, exercise, sleep and support from others.",
                ["Eisenhower matrix sorts tasks into urgent/important combinations.",
                 "Planning ahead, setting deadlines and avoiding multitasking reduce wasted time.",
                 "Procrastination is delaying tasks without good reason.",
                 "Healthy ways to manage stress: regular exercise, enough sleep, hobbies and talking to someone you trust.",
                 "Seek professional help if stress feels unmanageable."],
                ["Eisenhower matrix: Do first (urgent + important), Schedule (important), Delegate (urgent), Drop (neither)"],
                [S("What is procrastination?"), S("What is the Eisenhower matrix?"), S("Define stress. Give two causes."),
                 L("Explain time management techniques for students."), L("Discuss the causes, effects and management of stress."),
                 L("Explain work-life balance and why it matters.")]),
        chapter("Professional Skills: Resume, Group Discussion and Interview",
                ["Resume and CV writing", "Cover letter", "Email etiquette", "Group discussion techniques", "Types of interviews", "Preparing for an interview", "Presentation skills"],
                "Professional skills help you get and keep a job. A resume should be short, clear and honest; group discussions test communication and teamwork; interviews test knowledge and attitude.",
                ["A fresher's resume is usually one page: contact details, objective, education, projects, skills, achievements.",
                 "In a group discussion listen, make short and relevant points, and respect others' views.",
                 "Prepare for an interview by researching the company and practising common questions.",
                 "Emails should have a clear subject line, polite greeting and a short body.",
                 "Presentations should have a clear opening, body and conclusion with limited text per slide."],
                ["STAR method for interview answers: Situation, Task, Action, Result"],
                [S("What is the difference between a resume and a CV?"), S("List the dos and don'ts of a group discussion."), S("What is the STAR method?"),
                 L("Explain the format of a good resume and prepare one for a fresher."), L("Explain the types of interviews and tips for facing them."),
                 L("Explain the elements of effective presentation skills."),
                 N("Write a professional email to your professor requesting an extension for an assignment.", "Include a clear subject, greeting, reason, request and thanks.")]),
    ],
}


SUBJECTS = [
    to_subject(ENVIRONMENT, ["Environmental Studies - Erach Bharucha (Universities Press / UGC)", "Environmental Studies - Anubha Kaushik & C.P. Kaushik (New Age)"]),
    to_subject(SOFT_SKILLS, ["Soft Skills - K. Alex (S. Chand)", "Developing Communication Skills - Krishna Mohan & Meera Banerji (Macmillan)"]),
]
